### ISSUE TITLE
Http bug report

### ISSUE THREAD

**Issue by Eri-AntLer** [ericsson-mts/mts#17]
Two bugs have been detected :

* After an error occurs (launch 994_http_web_client and wait), several tests don't work anymore.  Messages are still exchanged but the last one doesn't reach the client.

* 811_auto-reconnection test can fail if you launch it numerous times right after starting mts . The server try to send a message using a channel it just closed. The test won't work anymore if you try launching it again.

**Comment by egwepas** [comment]
Fixed with #24
