### ISSUE TITLE
unable to receive SIP Requests in a new dialogue

### ISSUE THREAD

**Issue by horzoli** [ericsson-mts/mts#20]
Hi,

just started to work with MTS but unfortunately I am not able to receive SIP messages in new dialogue. 200 OK for my Requests are received properly regarding the Logs but the as I am waiting for a new Request from the Application servers I get timeout even if I see the SIP Request sent by the AS in a tcpdump.
I have set the listenpoint.LOCAL_PORT = 5062 in the sip.properties
I have tried to insert both of my dialogues into the same UAC.xml:
SIP MESSAGE -->
<-- 200 OK
then
waiting for <--SIP MESSAGE with:
<receivemessagesip request="true" type="MESSAGE" name="Waiting for MESSAGE with FD URI"></receivemessagesip>

but all I get is timeout.

I also tried the same with relocating the second dialogue waiting for the SIP MESSAGE in the UAS.xml but I get the same result.

If I try to start with
<createlistenpointsip localport="5062" name="terminal" transport="UDP" localhost="172.16.74.112">

then I get immediately an exception "address already in use"</createlistenpointsip>
Am I missing some configuration to be able to receive a SIP Request in a new dialouge from my Application Server?

Application Log (test without createlisteningpointsip) is attached.

Thank you in advance'
[application_logs.zip](https://github.com/ericsson-mts/mts/files/2481520/application_logs.zip)

**Comment by tfcardoso** [comment]
It seems you are receiving the response but not catching it on any scenario:

    WARN;PROTOCOL;Routing: could not route message by scenario routingName [5062, , SIP]

**Comment by horzoli** [comment]
Hi,

yes I am aware of that. I have also seen this line in the log.
My question is then how to avoid it? What do I need to be able to receive a
new incoming SIP request issued by the Application Server?
I guess in my case I do not need a UAS.xml, only an UAC.xml because I have
only one client comminucationg with a Server. Or do I?

I have already copied the Test from the
tutorial/ims/Terminal name="Message_A_vers_B" but this was a dead-end as I
got the very same error while waiting for an incoming SIP - MESSAGE

**Comment by tfcardoso** [comment]
You have to try to launch one scenario with the proper name to catch the routing that MTS does. I'm actually still having some problems understanding how to catch some responses where I do not have control of the "to" or "session" field.

You case seems more simple, have you tried using the default.xml scenario:

    <testcase name="default" interruptible="false" state="true">
        <runProfile>
            <step time="0" period="0" />
            <end delay="[YourTestTimeOut]" />
        </runProfile>
        <scenario name="default">default.xml</scenario>
    </testcase>

**Comment by horzoli** [comment]
Up till now I haven't tried the default.xml, however I cannot find it among the installed testcases.
I was using the follwong test file without runProfile settings:

    <testcase description="test sip" name="MCData_FD_URI_Discovery" state="true">
        <parameter name="[waitSemaphore]" operation="set" value="false"/>
        <scenario file="../../sip/105_sip_message_MCData/UAC.xml" name="alice" routingName="alice"/>
		<scenario file="../../sip/105_sip_message_MCData/UAS.xml" name="bob" routingName="bob"/>
    </testcase>

now UAS.xml would be the scenario waiting for the SIP MESSAGE initiated by the ApplicationServer.

However I do not know how to tell the MTS that the incoming SIP MESSAGE belongs to this UAS.xml scenario. It has its own listening point listening to the PORT where the SIP MESSGE comes. What else is missing from the scenario?

**Comment by GegeFR** [comment]
Hello,

A listenpoint does not "belong" to a scenario. It's been opened by him but
there is no specific link.

To route incoming requests the only thing that matters is ;
 - what is the key extracted from incoming requests
 - what are the name of your scenarios

From what i can see the keys extracted are : the port of the listenpoint
that received the message and the protocol of the message.

So, if you want your scenario to receive those incoming requests, its
routingName should literally be "5060" (or whatever port you chose) or
"SIP".

If you want multiple scenarios to run at the same time and have a more
precise routing, then you will have to extract another key than the one
configured by default, maybe the request type (INVITE, MESSAGE, ...) or the
recipient (sip-uri of "To" header per example)

And yes you probably only need one scenario.

Another precision : when receiving a response of a request sent by MTS
there is an automatic (but it can be disabled) behavior, when the protocol
supports transactions (a way to link a response to its request) ; by
default the response will be routed to the scenario that sent tbe request.

Hope it will help you.

**Comment by horzoli** [comment]
Yessssss that was exactly the info I was missing! 
Now my test works fine!
Thanks a lot for helping!

**Comment by egwepas** [comment]
Great !

You're welcome :-)

**Comment by horzoli** [comment]
Hi again!

Did not find any more proper possibility to ask a related question thant this closed ticket. 
I am still struggling with message routing to the correct scenario. This time it is about SIP call where with an AS in B2B position so the calls from the UAC scenario are forwarded to the UAS scenario.
I just need to forward the incoming INVITEs to the correct scenario based on e.g. the "To:" field because now routing based on the dest port does not work... all calls are routed to the same dest Port where mts is listening.
You mentioned in your comment:

_If you want multiple scenarios to run at the same time and have a more
precise routing, then you will have to extract another key than the one
configured by default, maybe the request type (INVITE, MESSAGE, ...) or the
recipient (sip-uri of "To" header per example)_

but how can I set the parameter to be extracted?

and why does e.g. the tutorial/demos/2-sip-load-rtp work? I cannot see there anything special to be extracted but the routing name used for each testcase is:
routingName="[number][invitee]
which is for the first testcase: 016666
Where is it then extracted from on the receiving side?

If I set the routing name to the exact "To:" field in my test:

<scenario file="UAC_B.xml" name="Boldal" routingName="sip:+435025510002@test.net"/>
it does not work, I get the following well know error:

WARN;PROTOCOL;Routing: could not route message by scenario routingName [5062, testhzC, SIP]

and yes here I can see the port, the name of the listening point and the protocol.

Could you please guide me to set a more precise routing, other than the dest port?

Thanks!
Zoltan
