### ISSUE TITLE
Regression noted on sending http request

### ISSUE THREAD

**Issue by npenna22** [ericsson-mts/mts#35]
By validating the integration of the MTS release 6.6.2 in our environment, I think I have found a regression on sending http request compared to version 6.4.5.

At first glance, this would impact http request queries on put method.

Here is a trace of running a testcase:
2425;14.08.2019 11:51:18 136;INFO;CORE;<log level="INFO">INFO : Envoi Req PUT /phones/{mac}</log>;
2426;14.08.2019 11:51:18 136;INFO;USER;INFO : Envoi Req PUT /phones/{mac};
2427;14.08.2019 11:51:18 136;INFO;CORE;Write in Scenariolog with the level = INFO the message  INFO : Envoi Req PUT /phones/{mac};
2428;14.08.2019 11:51:18 136;INFO;PROTOCOL;<sendMessageHTTP name="Send PUT" remoteURL="[bt-url]">
                                                                                        <![CDATA[
                                                                                                PUT /phones/[bt-mac-addr] HTTP/1.1
                                                                                                        ]]>
                                                                                </sendMessageHTTP>;

Here are now the application logs:
1859;14.08.2019 11:51:11 551;INFO;PARAM;SET [testcase:Forwarder_Number] => [1][[Forwarder]_Number]];
1868;14.08.2019 11:51:11 551;INFO;PARAM;SET [testcase:Caller_Number] => [1][789143245];
1883;14.08.2019 11:51:11 570;INFO;PARAM;SET [testcase:Callee_Number] => [1][[Callee]_Number]];
2376;14.08.2019 11:51:18 123;INFO;CALLFLOW;SEND>>> msg HTTP > GET
                                            GET /phones/88:75:98:06:92:57/service HTTP/1.1
                                            <MESSAGE transactionId ="5">;
2379;14.08.2019 11:51:18 127;INFO;PROTOCOL;Receive a response (response time = 0.004 s) for the transaction : GET_in / 200_out (TRANSACTION_ID=5);
2380;14.08.2019 11:51:18 127;INFO;PROTOCOL;Routing: route the received response by TRANSACTION_ID to "Mobile4G_Sg2" (TRANSACTION_ID=5).;
2381;14.08.2019 11:51:18 127;INFO;CALLFLOW;>>>RECEIVE msg HTTP > GET > 200
                                            HTTP/1.1 200 OK
                                            <MESSAGE transactionId ="5">;
2429;14.08.2019 11:51:18 137;WARN;PROTOCOL;Error while sending message
                                            CAUSE: Length required

                                            Complete stack :
                                                org.apache.hc.core5.http.LengthRequiredException: Length required
                                                org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:150)
                                                com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage(SocketClientHttp.java:106)
                                                com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage(ChannelHttp.java:121)
                                                com.devoteam.srit.xmlloader.core.protocol.Stack.sendMessage(Stack.java:696)
                                                com.devoteam.srit.xmlloader.http.StackHttp.sendMessage(StackHttp.java:365)
                                                com.devoteam.srit.xmlloader.core.protocol.Stack.sendMessageException(Stack.java:868)
                                                com.devoteam.srit.xmlloader.core.protocol.Stack.sendMessage(Stack.java:729)
                                                com.devoteam.srit.xmlloader.core.operations.protocol.OperationSendMessage.execute(OperationSendMessage.java:243)
                                                com.devoteam.srit.xmlloader.core.operations.Operation.executeAndStat(Operation.java:179)
                                                com.devoteam.srit.xmlloader.core.operations.basic.OperationSequence.execute(OperationSequence.java:88)
                                                com.devoteam.srit.xmlloader.core.operations.basic.OperationWhile.execute(OperationWhile.java:106)
                                                com.devoteam.srit.xmlloader.core.operations.Operation.executeAndStat(Operation.java:179)
                                                com.devoteam.srit.xmlloader.core.operations.basic.OperationSequence.execute(OperationSequence.java:88)
                                                com.devoteam.srit.xmlloader.core.operations.functions.Function.execute(Function.java:112)
                                                com.devoteam.srit.xmlloader.core.operations.basic.OperationCall.execute(OperationCall.java:118)
                                                com.devoteam.srit.xmlloader.core.operations.Operation.executeAndStat(Operation.java:179)
                                                com.devoteam.srit.xmlloader.core.operations.basic.OperationSequence.execute(OperationSequence.java:88)
                                                com.devoteam.srit.xmlloader.core.Scenario.executeScenario(Scenario.java:67)
                                                com.devoteam.srit.xmlloader.core.ScenarioRunner.run(ScenarioRunner.java:269)
                                                com.devoteam.srit.xmlloader.core.ThreadRunner.run(ThreadRunner.java:59)
                                            ;
2430;14.08.2019 11:51:18 137;WARN;PROTOCOL;Restoring connection and re-sending pending requests;
2431;14.08.2019 11:51:18 144;WARN;PROTOCOL;Error while sending message
                                            CAUSE: Length required

                                            Complete stack :
                                                org.apache.hc.core5.http.LengthRequiredException: Length required
                                                org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:150)
                                                com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage(SocketClientHttp.java:106)
                                                com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage(ChannelHttp.java:121)
                                                com.devoteam.srit.xmlloader.http.SocketClientHttp.restoreConnection(SocketClientHttp.java:83)
                                                com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage(SocketClientHttp.java:123)
                                                com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage(ChannelHttp.java:121)
                                                com.devoteam.srit.xmlloader.core.protocol.Stack.sendMessage(Stack.java:696)
                                                com.devoteam.srit.xmlloader.http.StackHttp.sendMessage(StackHttp.java:365)

Then MTS goes in infinite loop and the process is killed on exception:
java.lang.StackOverflowError
        at sun.net.spi.DefaultProxySelector $ 3.run (DefaultProxySelector.java:219)
        at sun.net.spi.DefaultProxySelector $ 3.run (DefaultProxySelector.java:209)
        at java.security.AccessController.doPrivileged (Native Method)
        at sun.net.spi.DefaultProxySelector.select (DefaultProxySelector.java:208)
        at java.net.SocksSocketImpl.connect (SocksSocketImpl.java:384)
        at java.net.Socket.connect (Socket.java:589)
        at java.net.Socket.connect (Socket.java:538)
        at com.devoteam.srit.xmlloader.http.bio.BIOChannelHttp.open (BIOChannelHttp.java:141)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.restoreConnection (SocketClientHttp.java:78)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage (SocketClientHttp.java:123)
        at com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage (ChannelHttp.java:121)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.restoreConnection (SocketClientHttp.java:83)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage (SocketClientHttp.java:123)
        at com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage (ChannelHttp.java:121)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.restoreConnection (SocketClientHttp.java:83)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage (SocketClientHttp.java:123)
        at com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage (ChannelHttp.java:121)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.restoreConnection (SocketClientHttp.java:83)
        at com.devoteam.srit.xmlloader.http.SocketClientHttp.sendMessage (SocketClientHttp.java:123)
        at com.devoteam.srit.xmlloader.http.ChannelHttp.sendMessage (ChannelHttp.java:121)

**Comment by ewenbaron** [comment]
Hi @npenna22,

After checking, i'll need your http message in order to investigate further

**Comment by npenna22** [comment]
Hi,

You will find in attached file the information requested

Regards,

Nicolas

**Comment by ewenbaron** [comment]
Thanks for the capture,

Maybe I also have the message that you put in your test case please ? (XML tag sendMessageHTTP)

Regards, 

Ewen

**Comment by npenna22** [comment]
Here is the script causing the problem :

**_<sendMessageHTTP name="Send PUT" remoteURL="[bt-url]">
	<![CDATA[
		PUT /phones/[bt-mac-addr] HTTP/1.1
			]]>
</sendMessageHTTP>

<receiveMessageHTTP name="Send 200 OK" type="PUT">
	<parameter name="[StatusCode]" operation="protocol.setFromMessage" value="firstline.statuscode"/>
</receiveMessageHTTP>_**

**Comment by ewenbaron** [comment]
Hi @npenna22 ,

After investigation, we find what caused regression and we fix it in https://github.com/ericsson-mts/mts/commit/b403c857f724c33985b715f70e31e6af4676d0cf

Note, there are some limitations right now (see https://github.com/ericsson-mts/mts/issues/37 and https://github.com/ericsson-mts/mts/issues/36) 

Regards,

Ewen
